import * as stylex from "@stylexjs/stylex";
export const styles = stylex.create({
  gpa0: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
  },
  gpa1: {
    width: "100%",
    maxWidth: "var(--container-xl)",
    borderRadius: "var(--radius)",
    backgroundColor: "var(--color-gray-800)",
    padding: "calc(var(--spacing)*6)",
    textAlign: "center",
    "--tw-shadow":
      "0 10px 15px -3px var(--tw-shadow-color,#0000001a),0 4px 6px -4px var(--tw-shadow-color,#0000001a)",
    boxShadow:
      "var(--tw-inset-shadow),var(--tw-inset-ring-shadow),var(--tw-ring-offset-shadow),var(--tw-ring-shadow),var(--tw-shadow)",
    paddingInline: null,
    paddingBlock: null,
  },
  gpa2: {
    marginBottom: "calc(var(--spacing)*2)",
    display: "block",
  },
  layout3: {
    backgroundColor: "#06070a",
    fontFamily:
      "ui-monospace,SFMono-Regular,Menlo,Monaco,Consolas,Liberation Mono,Courier New,monospace",
    color: "var(--color-white)",
  },
  Form4: {
    marginTop: "calc(var(--spacing)*6)",
  },
  Form5: {
    marginInline: "auto",
    width: "100%",
    maxWidth: "var(--container-5xl)",
    borderRadius: "calc(var(--radius) + 8px)",
    borderStyle: "var(--tw-border-style)",
    borderWidth: "1px",
    borderColor: "#314158b3",
    backgroundColor: "#0f172bb3",
    padding: "calc(var(--spacing)*5)",
    "--tw-shadow":
      "0 20px 25px -5px var(--tw-shadow-color,#0000001a),0 8px 10px -6px var(--tw-shadow-color,#0000001a)",
    boxShadow:
      "var(--tw-inset-shadow),var(--tw-inset-ring-shadow),var(--tw-ring-offset-shadow),var(--tw-ring-shadow),var(--tw-shadow)",
    "--tw-backdrop-blur": "blur(var(--blur-sm))",
    WebkitBackdropFilter:
      "var(--tw-backdrop-blur,)var(--tw-backdrop-brightness,)var(--tw-backdrop-contrast,)var(--tw-backdrop-grayscale,)var(--tw-backdrop-hue-rotate,)var(--tw-backdrop-invert,)var(--tw-backdrop-opacity,)var(--tw-backdrop-saturate,)var(--tw-backdrop-sepia,)",
    backdropFilter:
      "var(--tw-backdrop-blur,)var(--tw-backdrop-brightness,)var(--tw-backdrop-contrast,)var(--tw-backdrop-grayscale,)var(--tw-backdrop-hue-rotate,)var(--tw-backdrop-invert,)var(--tw-backdrop-opacity,)var(--tw-backdrop-saturate,)var(--tw-backdrop-sepia,)",
    paddingInline: null,
    paddingBlock: null,
  },
  Form6: {
    marginBottom: "calc(var(--spacing)*2)",
    textAlign: "center",
    fontSize: "var(--text-2xl)",
    lineHeight: "var(--tw-leading,var(--text-2xl--line-height))",
    "--tw-font-weight": "var(--font-weight-semibold)",
    fontWeight: "var(--font-weight-semibold)",
    "--tw-tracking": "var(--tracking-tight)",
    letterSpacing: "var(--tracking-tight)",
    color: "var(--color-slate-100)",
    "--tw-leading": null,
  },
  Form7: {
    marginBottom: "calc(var(--spacing)*6)",
    textAlign: "center",
    fontSize: "var(--text-sm)",
    lineHeight: "var(--tw-leading,var(--text-sm--line-height))",
    color: "var(--color-slate-400)",
    "--tw-leading": null,
  },
  Form8: {
    display: "grid",
    gap: "calc(var(--spacing)*4)",
  },
  Form9: {
    marginBottom: "calc(var(--spacing)*2)",
    display: "block",
    fontSize: "var(--text-sm)",
    lineHeight: "var(--tw-leading,var(--text-sm--line-height))",
    "--tw-font-weight": "var(--font-weight-medium)",
    fontWeight: "var(--font-weight-medium)",
    color: "var(--color-slate-200)",
    "--tw-leading": null,
  },
  Form10: {
    width: "100%",
    borderRadius: "var(--radius)",
    borderStyle: "var(--tw-border-style)",
    borderWidth: "1px",
    borderColor: "var(--color-slate-600)",
    backgroundColor: "var(--color-slate-800)",
    paddingInline: "calc(var(--spacing)*4)",
    paddingBlock: "calc(var(--spacing)*3)",
    fontSize: "var(--text-lg)",
    lineHeight: "var(--tw-leading,var(--text-lg--line-height))",
    color: "var(--color-slate-100)",
    "--tw-shadow": "inset 0 2px 4px 0 var(--tw-shadow-color,#0000000d)",
    boxShadow:
      "var(--tw-inset-shadow),var(--tw-inset-ring-shadow),var(--tw-ring-offset-shadow),var(--tw-ring-shadow),var(--tw-shadow)",
    transitionProperty:
      "color,background-color,border-color,outline-color,text-decoration-color,fill,stroke,--tw-gradient-from,--tw-gradient-via,--tw-gradient-to",
    transitionTimingFunction:
      "var(--tw-ease,var(--default-transition-timing-function))",
    transitionDuration: "var(--tw-duration,var(--default-transition-duration))",
    "--tw-leading": null,
  },
  Form11: {
    marginTop: "calc(var(--spacing)*5)",
    width: "100%",
    touchAction: "manipulation",
    borderRadius: "var(--radius)",
    backgroundColor: "var(--color-emerald-600)",
    paddingInline: "calc(var(--spacing)*4)",
    paddingBlock: "calc(var(--spacing)*3)",
    fontSize: "var(--text-base)",
    lineHeight: "var(--tw-leading,var(--text-base--line-height))",
    "--tw-font-weight": "var(--font-weight-semibold)",
    fontWeight: "var(--font-weight-semibold)",
    color: "var(--color-white)",
    transitionProperty:
      "color,background-color,border-color,outline-color,text-decoration-color,fill,stroke,--tw-gradient-from,--tw-gradient-via,--tw-gradient-to",
    transitionTimingFunction:
      "var(--tw-ease,var(--default-transition-timing-function))",
    transitionDuration: "var(--tw-duration,var(--default-transition-duration))",
    "--tw-leading": null,
  },
  Form12: {
    marginTop: "calc(var(--spacing)*4)",
    borderRadius: "var(--radius)",
    borderStyle: "var(--tw-border-style)",
    borderWidth: "1px",
    borderColor: "#fb2c3666",
    backgroundColor: "#46080999",
    padding: "calc(var(--spacing)*3)",
    fontSize: "var(--text-sm)",
    lineHeight: "var(--tw-leading,var(--text-sm--line-height))",
    color: "var(--color-red-100)",
    paddingInline: null,
    paddingBlock: null,
    "--tw-leading": null,
  },
  Form13: {
    marginTop: "calc(var(--spacing)*6)",
  },
  Form14: {
    borderRadius: "calc(var(--radius) + 4px)",
    borderStyle: "var(--tw-border-style)",
    borderWidth: "1px",
    borderColor: "var(--color-slate-700)",
    backgroundColor: "#1d293db3",
    padding: "calc(var(--spacing)*4)",
    paddingInline: null,
    paddingBlock: null,
  },
  Form15: {
    textAlign: "center",
    fontSize: "var(--text-lg)",
    lineHeight: "var(--tw-leading,var(--text-lg--line-height))",
    color: "var(--color-slate-100)",
    "--tw-leading": null,
  },
  Form16: {
    marginLeft: "calc(var(--spacing)*2)",
    "--tw-font-weight": "var(--font-weight-bold)",
    fontWeight: "var(--font-weight-bold)",
    color: "var(--color-amber-300)",
    "--tw-numeric-spacing": "tabular-nums",
    fontVariantNumeric:
      "var(--tw-ordinal,)var(--tw-slashed-zero,)var(--tw-numeric-figure,)var(--tw-numeric-spacing,)var(--tw-numeric-fraction,)",
  },
  Form17: {
    marginTop: "calc(var(--spacing)*2)",
    textAlign: "center",
    fontSize: "var(--text-xs)",
    lineHeight: "var(--tw-leading,var(--text-xs--line-height))",
    color: "var(--color-slate-400)",
    "--tw-leading": null,
  },
  Form18: {
    marginTop: "calc(var(--spacing)*10)",
    marginBottom: "calc(var(--spacing)*2)",
    textAlign: "center",
    "--tw-font-weight": "var(--font-weight-semibold)",
    fontWeight: "var(--font-weight-semibold)",
    color: "var(--color-white)",
  },
  Form19: {
    color: "var(--color-yellow-400)",
    transitionProperty: "all",
    transitionTimingFunction:
      "var(--tw-ease,var(--default-transition-timing-function))",
    transitionDuration: "var(--tw-duration,var(--default-transition-duration))",
  },
  met20: {
    borderColor: "var(--color-slate-700)",
    backgroundColor: "var(--color-slate-900)",
    color: "var(--color-slate-100)",
  },
  met21: {
    fontSize: "var(--text-xl)",
    lineHeight: "var(--tw-leading,var(--text-xl--line-height))",
    color: "var(--color-amber-300)",
    "--tw-leading": null,
  },
  met22: {
    fontSize: "var(--text-sm)",
    lineHeight: "var(--leading-relaxed)",
    "--tw-leading": "var(--leading-relaxed)",
    color: "var(--color-slate-300)",
  },
  met23: {
    display: "block",
  },
  met24: {
    display: "block",
    "--tw-font-weight": "var(--font-weight-medium)",
    fontWeight: "var(--font-weight-medium)",
    color: "var(--color-slate-200)",
  },
  met25: {
    width: "100%",
    backgroundColor: "var(--color-emerald-600)",
    color: "var(--color-white)",
  },
  met26: {
    minHeight: "100vh",
    overflowX: "hidden",
    backgroundColor: "#06070a",
    paddingInline: "calc(var(--spacing)*4)",
    paddingBlock: "calc(var(--spacing)*8)",
  },
  met27: {
    marginInline: "auto",
    width: "100%",
    maxWidth: "var(--container-6xl)",
  },
  met28: {
    borderRadius: "calc(var(--radius) + 12px)",
    borderColor: "#31415899",
    "--tw-gradient-position": "to bottom",
    backgroundImage: "linear-gradient(var(--tw-gradient-stops))",
    "--tw-gradient-from": "var(--color-slate-900)",
    "--tw-gradient-stops":
      "var(--tw-gradient-via-stops,var(--tw-gradient-position),var(--tw-gradient-from)var(--tw-gradient-from-position),var(--tw-gradient-to)var(--tw-gradient-to-position))",
    "--tw-gradient-via": "var(--color-slate-900)",
    "--tw-gradient-via-stops":
      "var(--tw-gradient-position),var(--tw-gradient-from)var(--tw-gradient-from-position),var(--tw-gradient-via)var(--tw-gradient-via-position),var(--tw-gradient-to)var(--tw-gradient-to-position)",
    "--tw-gradient-to": "var(--color-slate-950)",
    "--tw-shadow": "0 20px 80px var(--tw-shadow-color,#02061799)",
    boxShadow:
      "var(--tw-inset-shadow),var(--tw-inset-ring-shadow),var(--tw-ring-offset-shadow),var(--tw-ring-shadow),var(--tw-shadow)",
  },
  met29: {
    padding: "calc(var(--spacing)*4)",
    paddingInline: null,
    paddingBlock: null,
  },
  home30: {
    marginTop: "calc(var(--spacing)*8)",
    marginBottom: "calc(var(--spacing)*18)",
    paddingInline: "calc(var(--spacing)*10)",
    textAlign: "justify",
  },
  home31: {},
  home32: {
    fontSize: "var(--text-2xl)",
    lineHeight: "var(--tw-leading,var(--text-2xl--line-height))",
    "--tw-font-weight": "var(--font-weight-bold)",
    fontWeight: "var(--font-weight-bold)",
    "--tw-leading": null,
  },
  home33: {
    color: "var(--color-gray-300)",
  },
  home34: {
    marginLeft: "calc(var(--spacing)*4)",
    listStylePosition: "inside",
    listStyleType: "disc",
    color: "var(--color-gray-300)",
  },
  home35: {
    color: "var(--color-white)",
    transitionProperty: "all",
    transitionTimingFunction:
      "var(--tw-ease,var(--default-transition-timing-function))",
    transitionDuration: "var(--tw-duration,var(--default-transition-duration))",
  },
  home36: {
    color: "var(--color-yellow-500)",
    transitionProperty: "all",
    transitionTimingFunction:
      "var(--tw-ease,var(--default-transition-timing-function))",
    transitionDuration: "var(--tw-duration,var(--default-transition-duration))",
  },
  BranchesDisplay37: {
    marginTop: "calc(var(--spacing)*4)",
    borderRadius: "calc(var(--radius) + 4px)",
    borderStyle: "var(--tw-border-style)",
    borderWidth: "1px",
    borderColor: "#fb2c3666",
    backgroundColor: "#460809b3",
    padding: "calc(var(--spacing)*4)",
    textAlign: "center",
    color: "var(--color-red-100)",
    paddingInline: null,
    paddingBlock: null,
  },
  BranchesDisplay38: {
    fontSize: "var(--text-sm)",
    lineHeight: "var(--tw-leading,var(--text-sm--line-height))",
    "--tw-leading": null,
  },
  BranchesDisplay39: {
    marginTop: "calc(var(--spacing)*4)",
  },
  BranchesDisplay40: {
    marginBottom: "calc(var(--spacing)*3)",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "calc(var(--spacing)*3)",
  },
  BranchesDisplay41: {
    fontSize: "var(--text-lg)",
    lineHeight: "var(--tw-leading,var(--text-lg--line-height))",
    "--tw-font-weight": "var(--font-weight-semibold)",
    fontWeight: "var(--font-weight-semibold)",
    color: "var(--color-slate-100)",
    "--tw-leading": null,
  },
  BranchesDisplay42: {
    marginBottom: "calc(var(--spacing)*4)",
    overflow: "hidden",
    borderRadius: "calc(var(--radius) + 4px)",
    borderStyle: "var(--tw-border-style)",
    borderWidth: "1px",
    borderColor: "var(--color-slate-700)",
    backgroundColor: "#0f172bb3",
  },
  BranchesDisplay43: {
    display: "flex",
    width: "100%",
    touchAction: "manipulation",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "calc(var(--spacing)*3)",
    borderBottomStyle: "var(--tw-border-style)",
    borderBottomWidth: "1px",
    borderColor: "var(--color-slate-700)",
    backgroundColor: "#009767e6",
    paddingInline: "calc(var(--spacing)*4)",
    paddingBlock: "calc(var(--spacing)*3)",
    textAlign: "left",
    color: "var(--color-white)",
    transitionProperty:
      "color,background-color,border-color,outline-color,text-decoration-color,fill,stroke,--tw-gradient-from,--tw-gradient-via,--tw-gradient-to",
    transitionTimingFunction:
      "var(--tw-ease,var(--default-transition-timing-function))",
    transitionDuration: "var(--tw-duration,var(--default-transition-duration))",
  },
  BranchesDisplay44: {
    fontSize: "var(--text-base)",
    lineHeight: "var(--tw-leading,var(--text-base--line-height))",
    "--tw-font-weight": "var(--font-weight-semibold)",
    fontWeight: "var(--font-weight-semibold)",
    "--tw-leading": null,
  },
  BranchesDisplay45: {
    borderRadius: "3.40282e38px",
    backgroundColor: "#0003",
    paddingInline: "calc(var(--spacing)*2)",
    paddingBlock: "calc(var(--spacing)*1)",
    fontSize: "var(--text-xs)",
    lineHeight: "var(--tw-leading,var(--text-xs--line-height))",
    "--tw-font-weight": "var(--font-weight-medium)",
    fontWeight: "var(--font-weight-medium)",
    "--tw-leading": null,
  },
  BranchesDisplay46: {
    padding: "calc(var(--spacing)*3)",
    paddingInline: null,
    paddingBlock: null,
  },
  BranchesDisplay47: {
    display: "grid",
    gap: "calc(var(--spacing)*2)",
  },
  BranchesDisplay48: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: "calc(var(--spacing)*3)",
    borderRadius: "var(--radius)",
    borderStyle: "var(--tw-border-style)",
    borderWidth: "1px",
    borderColor: "var(--color-slate-700)",
    backgroundColor: "#1d293db3",
    paddingInline: "calc(var(--spacing)*3)",
    paddingBlock: "calc(var(--spacing)*2)",
  },
  BranchesDisplay49: {
    minWidth: "calc(var(--spacing)*0)",
    fontSize: "var(--text-sm)",
    lineHeight: "var(--tw-leading,var(--text-sm--line-height))",
    overflowWrap: "break-word",
    color: "var(--color-slate-100)",
    "--tw-leading": null,
  },
  BranchesDisplay50: {
    flexShrink: "0",
    borderRadius: "calc(var(--radius) - 2px)",
    backgroundColor: "var(--color-slate-700)",
    paddingInline: "calc(var(--spacing)*2)",
    paddingBlock: "calc(var(--spacing)*1)",
    fontSize: "var(--text-xs)",
    lineHeight: "var(--tw-leading,var(--text-xs--line-height))",
    "--tw-font-weight": "var(--font-weight-semibold)",
    fontWeight: "var(--font-weight-semibold)",
    color: "var(--color-amber-300)",
    "--tw-numeric-spacing": "tabular-nums",
    fontVariantNumeric:
      "var(--tw-ordinal,)var(--tw-slashed-zero,)var(--tw-numeric-figure,)var(--tw-numeric-spacing,)var(--tw-numeric-fraction,)",
    "--tw-leading": null,
  },
  HowItWorksDropdown51: {
    marginInline: "auto",
    marginBottom: "calc(var(--spacing)*8)",
    maxWidth: "var(--container-4xl)",
  },
  HowItWorksDropdown52: {
    marginBottom: "calc(var(--spacing)*4)",
    cursor: "pointer",
    textAlign: "center",
    color: "var(--color-white)",
    textDecorationLine: "underline",
    transitionProperty: "all",
    transitionTimingFunction:
      "var(--tw-ease,var(--default-transition-timing-function))",
    transitionDuration: "var(--tw-duration,var(--default-transition-duration))",
  },
  HowItWorksDropdown53: {
    borderRadius: "var(--radius)",
    backgroundColor: "var(--color-gray-900)",
    padding: "calc(var(--spacing)*6)",
    color: "var(--color-white)",
    paddingInline: null,
    paddingBlock: null,
  },
  HowItWorksDropdown54: {
    marginBottom: "calc(var(--spacing)*4)",
  },
  HowItWorksDropdown55: {
    marginBottom: "calc(var(--spacing)*4)",
    listStylePosition: "inside",
    listStyleType: "disc",
    textAlign: "left",
  },
  HowItWorksDropdown56: {
    marginBottom: "calc(var(--spacing)*4)",
    borderRadius: ".25rem",
    backgroundColor: "var(--color-gray-800)",
    padding: "calc(var(--spacing)*4)",
    textAlign: "center",
    paddingInline: null,
    paddingBlock: null,
  },
  HowItWorksDropdown57: {
    color: "var(--color-blue-400)",
    textDecorationLine: "underline",
  },
  HowItWorksDropdown58: {
    marginBottom: "calc(var(--spacing)*8)",
  },
  HowItWorksDropdown59: {
    marginBottom: "calc(var(--spacing)*4)",
    fontSize: "var(--text-2xl)",
    lineHeight: "var(--tw-leading,var(--text-2xl--line-height))",
    "--tw-font-weight": "var(--font-weight-semibold)",
    fontWeight: "var(--font-weight-semibold)",
    "--tw-leading": null,
  },
  HowItWorksDropdown60: {
    fontSize: "var(--text-base)",
    lineHeight: "var(--leading-relaxed)",
    "--tw-leading": "var(--leading-relaxed)",
  },
  HowItWorksDropdown61: {
    marginBottom: "calc(var(--spacing)*2)",
    fontSize: "var(--text-lg)",
    lineHeight: "var(--tw-leading,var(--text-lg--line-height))",
    "--tw-font-weight": "var(--font-weight-semibold)",
    fontWeight: "var(--font-weight-semibold)",
    "--tw-leading": null,
  },
  HowItWorksDropdown62: {
    marginBottom: "calc(var(--spacing)*2)",
  },
  HowItWorksDropdown63: {
    "--tw-font-weight": "var(--font-weight-semibold)",
    fontWeight: "var(--font-weight-semibold)",
  },
  HowItWorksDropdown64: {
    marginTop: "calc(var(--spacing)*2)",
    marginBottom: "calc(var(--spacing)*2)",
    marginLeft: "calc(var(--spacing)*4)",
    listStylePosition: "inside",
    listStyleType: "disc",
    color: "var(--color-gray-300)",
  },
  HowItWorksDropdown65: {
    "--tw-font-weight": "var(--font-weight-semibold)",
    fontWeight: "var(--font-weight-semibold)",
    color: "var(--color-yellow-300)",
  },
  HowItWorksDropdown66: {
    marginTop: "calc(var(--spacing)*2)",
    marginBottom: "calc(var(--spacing)*2)",
    "--tw-font-weight": "var(--font-weight-semibold)",
    fontWeight: "var(--font-weight-semibold)",
  },
  HowItWorksDropdown67: {
    marginLeft: "calc(var(--spacing)*4)",
    listStylePosition: "inside",
    listStyleType: "disc",
    color: "var(--color-gray-300)",
  },
  Navbar68: {
    borderRadius: ".25rem",
    borderStyle: "var(--tw-border-style)",
    borderWidth: "1px",
    borderColor: "var(--color-white)",
    paddingInline: "calc(var(--spacing)*4)",
    paddingBlock: "calc(var(--spacing)*1)",
    fontSize: "var(--text-lg)",
    lineHeight: "var(--tw-leading,var(--text-lg--line-height))",
    transitionProperty: "all",
    transitionTimingFunction:
      "var(--tw-ease,var(--default-transition-timing-function))",
    transitionDuration: "var(--tw-duration,var(--default-transition-duration))",
    "--tw-leading": null,
  },
  Navbar69: {
    position: "relative",
    marginTop: "calc(var(--spacing)*6)",
    marginBottom: "calc(var(--spacing)*5)",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: "calc(var(--spacing)*2)",
    paddingInline: "calc(var(--spacing)*4)",
  },
  Navbar70: {
    height: "calc(var(--spacing)*14)",
    width: "calc(var(--spacing)*14)",
    cursor: "pointer",
    objectFit: "contain",
  },
  Navbar71: {
    textAlign: "center",
    fontSize: "var(--text-3xl)",
    lineHeight: "var(--leading-tight)",
    "--tw-leading": "var(--leading-tight)",
    "--tw-font-weight": "var(--font-weight-bold)",
    fontWeight: "var(--font-weight-bold)",
  },
  Navbar72: {
    marginBottom: "calc(var(--spacing)*4)",
    textAlign: "center",
    fontSize: "var(--text-sm)",
    lineHeight: "var(--tw-leading,var(--text-sm--line-height))",
    "--tw-leading": null,
  },
  Navbar73: {
    marginBlock: "calc(var(--spacing)*5)",
    borderTopStyle: "var(--tw-border-style)",
    borderTopWidth: "2px",
    borderColor: "var(--color-white)",
  },
  Navbar74: {
    marginBottom: "calc(var(--spacing)*5)",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    gap: "calc(var(--spacing)*8)",
    textAlign: "center",
  },
  CourseList75: {
    backgroundColor: "var(--color-blue-600)",
  },
  CourseList76: {
    cursor: "pointer",
    borderRadius: "calc(var(--radius) - 2px)",
    padding: "calc(var(--spacing)*2)",
    fontSize: "var(--text-sm)",
    lineHeight: "var(--tw-leading,var(--text-sm--line-height))",
    transitionProperty: "all",
    transitionTimingFunction:
      "var(--tw-ease,var(--default-transition-timing-function))",
    transitionDuration: "var(--tw-duration,var(--default-transition-duration))",
    paddingInline: null,
    paddingBlock: null,
    "--tw-leading": null,
  },
  CourseList77: {
    pointerEvents: "none",
    maxHeight: "calc(var(--spacing)*0)",
    padding: "calc(var(--spacing)*0)",
    opacity: "0",
    paddingInline: null,
    paddingBlock: null,
  },
  CourseList78: {
    marginBottom: "calc(var(--spacing)*5)",
    maxHeight: "calc(var(--spacing)*96)",
    padding: "calc(var(--spacing)*4)",
    opacity: "1",
    paddingInline: null,
    paddingBlock: null,
  },
  CourseList79: {
    marginInline: "auto",
    display: "flex",
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    borderRadius: "calc(var(--radius) + 4px)",
    borderStyle: "var(--tw-border-style)",
    borderWidth: "1px",
    borderColor: "#fff6",
    backgroundColor: "var(--color-gray-700)",
    "--tw-shadow":
      "0 10px 15px -3px var(--tw-shadow-color,#0000001a),0 4px 6px -4px var(--tw-shadow-color,#0000001a)",
    boxShadow:
      "var(--tw-inset-shadow),var(--tw-inset-ring-shadow),var(--tw-ring-offset-shadow),var(--tw-ring-shadow),var(--tw-shadow)",
    transitionProperty: "all",
    transitionTimingFunction:
      "var(--tw-ease,var(--default-transition-timing-function))",
    transitionDuration: ".5s",
    "--tw-duration": ".5s",
  },
  CourseList80: {
    display: "grid",
    width: "100%",
    gridTemplateColumns: "repeat(3,minmax(0,1fr))",
    gridTemplateRows: "repeat(7,minmax(0,1fr))",
    gap: "calc(var(--spacing)*3)",
    textAlign: "center",
  },
  CycleSelect81: {
    cursor: "pointer",
    borderRadius: "calc(var(--radius) - 2px)",
    padding: "calc(var(--spacing)*1)",
    transitionProperty: "all",
    transitionTimingFunction:
      "var(--tw-ease,var(--default-transition-timing-function))",
    transitionDuration: "var(--tw-duration,var(--default-transition-duration))",
    paddingInline: null,
    paddingBlock: null,
  },
  CycleSelect82: {
    marginTop: "calc(var(--spacing)*2)",
    marginBottom: "calc(var(--spacing)*5)",
    maxHeight: "calc(var(--spacing)*20)",
    padding: "calc(var(--spacing)*3)",
    opacity: "1",
    paddingInline: null,
    paddingBlock: null,
  },
  CycleSelect83: {
    pointerEvents: "none",
    marginTop: "calc(var(--spacing)*0)",
    marginBottom: "calc(var(--spacing)*0)",
    maxHeight: "calc(var(--spacing)*0)",
    padding: "calc(var(--spacing)*0)",
    opacity: "0",
    paddingInline: null,
    paddingBlock: null,
  },
  CycleSelect84: {
    marginInline: "auto",
    display: "flex",
    width: "100%",
    justifyContent: "center",
    gap: "calc(var(--spacing)*4)",
    overflow: "hidden",
    borderRadius: "calc(var(--radius) + 8px)",
    borderStyle: "var(--tw-border-style)",
    borderWidth: "1px",
    borderColor: "#fff6",
    backgroundColor: "var(--color-gray-700)",
    "--tw-shadow":
      "0 10px 15px -3px var(--tw-shadow-color,#0000001a),0 4px 6px -4px var(--tw-shadow-color,#0000001a)",
    boxShadow:
      "var(--tw-inset-shadow),var(--tw-inset-ring-shadow),var(--tw-ring-offset-shadow),var(--tw-ring-shadow),var(--tw-shadow)",
    transitionProperty: "all",
    transitionTimingFunction:
      "var(--tw-ease,var(--default-transition-timing-function))",
    transitionDuration: ".5s",
    "--tw-duration": ".5s",
  },
  CycleSelect85: {
    marginBlock: "auto",
    display: "flex",
    width: "100%",
    flexDirection: "row",
    justifyContent: "space-evenly",
  },
  GpaTable86: {
    backgroundColor: "var(--color-zinc-900)",
  },
  GpaTable87: {
    opacity: "0",
  },
  GpaTable88: {
    opacity: "1",
  },
  GpaTable89: {
    marginBottom: "calc(var(--spacing)*6)",
    display: "flex",
    flexShrink: "1",
    justifyContent: "center",
    textAlign: "center",
    "--tw-drop-shadow-size":
      "drop-shadow(0 9px 7px var(--tw-drop-shadow-color,#0000001a))",
    "--tw-drop-shadow": "drop-shadow(var(--drop-shadow-xl))",
    filter:
      "var(--tw-blur,)var(--tw-brightness,)var(--tw-contrast,)var(--tw-grayscale,)var(--tw-hue-rotate,)var(--tw-invert,)var(--tw-saturate,)var(--tw-sepia,)var(--tw-drop-shadow,)",
    transitionProperty: "all",
    transitionTimingFunction:
      "var(--tw-ease,var(--default-transition-timing-function))",
    transitionDuration: ".5s",
    "--tw-duration": ".5s",
  },
  GpaTable90: {
    tableLayout: "auto",
    borderCollapse: "collapse",
    "--tw-drop-shadow-size":
      "drop-shadow(0 9px 7px var(--tw-drop-shadow-color,#0000001a))",
    "--tw-drop-shadow": "drop-shadow(var(--drop-shadow-xl))",
    filter:
      "var(--tw-blur,)var(--tw-brightness,)var(--tw-contrast,)var(--tw-grayscale,)var(--tw-hue-rotate,)var(--tw-invert,)var(--tw-saturate,)var(--tw-sepia,)var(--tw-drop-shadow,)",
    transitionProperty: "all",
    transitionTimingFunction:
      "var(--tw-ease,var(--default-transition-timing-function))",
    transitionDuration: ".5s",
    "--tw-duration": ".5s",
  },
  GpaTable91: {
    backgroundColor: "var(--color-zinc-900)",
    paddingBlock: "calc(var(--spacing)*10)",
  },
  GpaTable92: {
    pointerEvents: "none",
    opacity: "0",
  },
  GpaTable93: {
    transitionProperty: "all",
    transitionTimingFunction:
      "var(--tw-ease,var(--default-transition-timing-function))",
    transitionDuration: ".5s",
    "--tw-duration": ".5s",
  },
  GpaTable94: {
    marginBottom: "calc(var(--spacing)*4)",
    width: "100%",
    cursor: "pointer",
    borderRadius: "var(--radius)",
    backgroundColor: "var(--color-green-600)",
    paddingInline: "calc(var(--spacing)*4)",
    paddingBlock: "calc(var(--spacing)*2)",
    color: "var(--color-white)",
    transitionProperty:
      "color,background-color,border-color,outline-color,text-decoration-color,fill,stroke,--tw-gradient-from,--tw-gradient-via,--tw-gradient-to",
    transitionTimingFunction:
      "var(--tw-ease,var(--default-transition-timing-function))",
    transitionDuration: "var(--tw-duration,var(--default-transition-duration))",
  },
  GpaTable95: {
    display: "none",
  },
  GradingInfoDropdown96: {
    marginBottom: "calc(var(--spacing)*4)",
    cursor: "pointer",
    textAlign: "center",
    textDecorationLine: "underline",
    transitionProperty: "all",
    transitionTimingFunction:
      "var(--tw-ease,var(--default-transition-timing-function))",
    transitionDuration: "var(--tw-duration,var(--default-transition-duration))",
  },
  GradingInfoDropdown97: {
    borderRadius: "var(--radius)",
    backgroundColor: "var(--color-gray-900)",
    padding: "calc(var(--spacing)*6)",
    paddingInline: null,
    paddingBlock: null,
  },
  GradingInfoDropdown98: {
    marginBottom: "calc(var(--spacing)*4)",
    textAlign: "left",
    fontSize: "var(--text-xl)",
    lineHeight: "var(--tw-leading,var(--text-xl--line-height))",
    "--tw-font-weight": "var(--font-weight-bold)",
    fontWeight: "var(--font-weight-bold)",
    "--tw-leading": null,
  },
  GradingInfoDropdown99: {
    marginBottom: "calc(var(--spacing)*6)",
  },
  GradingInfoDropdown100: {
    marginBottom: "calc(var(--spacing)*2)",
    fontSize: "var(--text-lg)",
    lineHeight: "var(--tw-leading,var(--text-lg--line-height))",
    "--tw-font-weight": "var(--font-weight-semibold)",
    fontWeight: "var(--font-weight-semibold)",
    "--tw-leading": null,
  },
  GradingInfoDropdown101: {
    marginBottom: "calc(var(--spacing)*2)",
    color: "var(--color-gray-300)",
  },
  GradingInfoDropdown102: {
    marginBottom: "calc(var(--spacing)*2)",
    borderRadius: ".25rem",
    backgroundColor: "var(--color-gray-800)",
    padding: "calc(var(--spacing)*4)",
    textAlign: "center",
    paddingInline: null,
    paddingBlock: null,
  },
  GradingInfoDropdown103: {
    fontFamily:
      "ui-monospace,SFMono-Regular,Menlo,Monaco,Consolas,Liberation Mono,Courier New,monospace",
  },
  GradingInfoDropdown104: {
    marginTop: "calc(var(--spacing)*1)",
    marginLeft: "calc(var(--spacing)*4)",
    listStylePosition: "inside",
    listStyleType: "disc",
  },
  GradingInfoDropdown105: {
    marginLeft: "calc(var(--spacing)*1)",
    color: "var(--color-blue-400)",
    textDecorationLine: "underline",
  },
  HonorsCheck106: {
    marginInline: "auto",
    marginBottom: "calc(var(--spacing)*4)",
    display: "flex",
    justifyContent: "center",
    borderRadius: "var(--radius)",
    borderStyle: "var(--tw-border-style)",
    borderWidth: "1px",
    borderColor: "#fff6",
    backgroundColor: "var(--color-gray-700)",
    padding: "calc(var(--spacing)*3)",
    "--tw-shadow":
      "0 10px 15px -3px var(--tw-shadow-color,#0000001a),0 4px 6px -4px var(--tw-shadow-color,#0000001a)",
    boxShadow:
      "var(--tw-inset-shadow),var(--tw-inset-ring-shadow),var(--tw-ring-offset-shadow),var(--tw-ring-shadow),var(--tw-shadow)",
    transitionProperty: "all",
    transitionTimingFunction:
      "var(--tw-ease,var(--default-transition-timing-function))",
    transitionDuration: ".5s",
    "--tw-duration": ".5s",
    paddingInline: null,
    paddingBlock: null,
  },
  HonorsCheck107: {
    display: "flex",
    alignItems: "center",
  },
  HonorsCheck108: {
    height: "calc(var(--spacing)*5)",
    width: "calc(var(--spacing)*5)",
    cursor: "pointer",
    borderRadius: ".25rem",
    borderColor: "var(--color-gray-600)",
    backgroundColor: "var(--color-gray-700)",
    color: "var(--color-blue-600)",
    "--tw-ring-offset-color": "var(--color-gray-800)",
  },
  HonorsCheck109: {
    marginLeft: "calc(var(--spacing)*3)",
    cursor: "pointer",
    fontSize: "var(--text-sm)",
    lineHeight: "var(--tw-leading,var(--text-sm--line-height))",
    "--tw-font-weight": "var(--font-weight-medium)",
    fontWeight: "var(--font-weight-medium)",
    color: "var(--color-gray-300)",
    WebkitUserSelect: "none",
    userSelect: "none",
    "--tw-leading": null,
  },
  SemButton110: {
    marginBottom: "calc(var(--spacing)*4)",
    cursor: "pointer",
    borderRadius: "var(--radius)",
    borderStyle: "var(--tw-border-style)",
    borderWidth: "1px",
    borderColor: "var(--color-gray-700)",
    backgroundColor: "var(--color-gray-600)",
    paddingInline: "calc(var(--spacing)*6)",
    paddingBlock: "calc(var(--spacing)*3)",
    "--tw-font-weight": "var(--font-weight-bold)",
    fontWeight: "var(--font-weight-bold)",
    color: "var(--color-white)",
    "--tw-shadow":
      "0 4px 6px -1px var(--tw-shadow-color,#0000001a),0 2px 4px -2px var(--tw-shadow-color,#0000001a)",
    boxShadow:
      "var(--tw-inset-shadow),var(--tw-inset-ring-shadow),var(--tw-ring-offset-shadow),var(--tw-ring-shadow),var(--tw-shadow)",
    transitionProperty: "all",
    transitionTimingFunction:
      "var(--tw-ease,var(--default-transition-timing-function))",
    transitionDuration: "var(--tw-duration,var(--default-transition-duration))",
  },
  SemButton111: {
    rotate: "180deg",
  },
  SemButton112: {
    rotate: "none",
  },
  SemButton113: {
    marginLeft: "calc(var(--spacing)*2)",
    display: "inline-block",
    transform:
      "var(--tw-rotate-x,)var(--tw-rotate-y,)var(--tw-rotate-z,)var(--tw-skew-x,)var(--tw-skew-y,)",
    transitionProperty: "all",
    transitionTimingFunction:
      "var(--tw-ease,var(--default-transition-timing-function))",
    transitionDuration: ".3s",
    "--tw-duration": ".3s",
  },
  SemPicker114: {
    cursor: "pointer",
    borderRadius: "calc(var(--radius) - 2px)",
    padding: "calc(var(--spacing)*3)",
    transitionProperty: "all",
    transitionTimingFunction:
      "var(--tw-ease,var(--default-transition-timing-function))",
    transitionDuration: "var(--tw-duration,var(--default-transition-duration))",
    paddingInline: null,
    paddingBlock: null,
  },
  SemPicker115: {
    marginTop: "calc(var(--spacing)*2)",
    marginBottom: "calc(var(--spacing)*4)",
    maxHeight: "calc(var(--spacing)*96)",
    opacity: "1",
  },
  SemPicker116: {
    pointerEvents: "none",
    marginTop: "calc(var(--spacing)*0)",
    marginBottom: "calc(var(--spacing)*0)",
    maxHeight: "calc(var(--spacing)*0)",
    opacity: "0",
  },
  SemPicker117: {
    marginInline: "auto",
    display: "flex",
    width: "calc(var(--spacing)*72)",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    borderRadius: "calc(var(--radius) + 4px)",
    borderStyle: "var(--tw-border-style)",
    borderWidth: "1px",
    borderColor: "#fff6",
    backgroundColor: "var(--color-gray-700)",
    padding: "calc(var(--spacing)*3)",
    "--tw-shadow":
      "0 10px 15px -3px var(--tw-shadow-color,#0000001a),0 4px 6px -4px var(--tw-shadow-color,#0000001a)",
    boxShadow:
      "var(--tw-inset-shadow),var(--tw-inset-ring-shadow),var(--tw-ring-offset-shadow),var(--tw-ring-shadow),var(--tw-shadow)",
    transitionProperty: "all",
    transitionTimingFunction:
      "var(--tw-ease,var(--default-transition-timing-function))",
    transitionDuration: ".5s",
    "--tw-duration": ".5s",
    paddingInline: null,
    paddingBlock: null,
  },
  SemPicker118: {
    display: "grid",
    width: "100%",
    gridTemplateColumns: "repeat(4,minmax(0,1fr))",
    gridTemplateRows: "repeat(2,minmax(0,1fr))",
    gap: "calc(var(--spacing)*3)",
    textAlign: "center",
  },
  StreamSelect119: {
    pointerEvents: "none",
    marginTop: "calc(var(--spacing)*0)",
    marginBottom: "calc(var(--spacing)*0)",
    maxHeight: "calc(var(--spacing)*0)",
    padding: "calc(var(--spacing)*0)",
    opacity: "0",
    paddingInline: null,
    paddingBlock: null,
  },
  StreamSelect120: {
    marginTop: "calc(var(--spacing)*2)",
    marginBottom: "calc(var(--spacing)*5)",
    maxHeight: "calc(var(--spacing)*20)",
    padding: "calc(var(--spacing)*3)",
    opacity: "1",
    paddingInline: null,
    paddingBlock: null,
  },
  button121: {
    display: "inline-flex",
    flexShrink: "0",
    alignItems: "center",
    justifyContent: "center",
    gap: "calc(var(--spacing)*2)",
    borderRadius: "calc(var(--radius) - 2px)",
    fontSize: "var(--text-sm)",
    lineHeight: "var(--tw-leading,var(--text-sm--line-height))",
    "--tw-font-weight": "var(--font-weight-medium)",
    fontWeight: "var(--font-weight-medium)",
    whiteSpace: "nowrap",
    transitionProperty: "all",
    transitionTimingFunction:
      "var(--tw-ease,var(--default-transition-timing-function))",
    transitionDuration: "var(--tw-duration,var(--default-transition-duration))",
    "--tw-outline-style": "none",
    outlineStyle: "none",
    "--tw-leading": null,
  },
  button122: {
    backgroundColor: "var(--primary)",
    color: "var(--primary-foreground)",
  },
  button123: {
    backgroundColor: "var(--destructive)",
    color: "var(--color-white)",
  },
  button124: {
    borderStyle: "var(--tw-border-style)",
    borderWidth: "1px",
    backgroundColor: "var(--background)",
    "--tw-shadow": "0 1px 2px 0 var(--tw-shadow-color,#0000000d)",
    boxShadow:
      "var(--tw-inset-shadow),var(--tw-inset-ring-shadow),var(--tw-ring-offset-shadow),var(--tw-ring-shadow),var(--tw-shadow)",
  },
  button125: {
    backgroundColor: "var(--secondary)",
    color: "var(--secondary-foreground)",
  },
  button126: {},
  button127: {
    color: "var(--primary)",
    textUnderlineOffset: "4px",
  },
  button128: {
    height: "calc(var(--spacing)*9)",
    paddingInline: "calc(var(--spacing)*4)",
    paddingBlock: "calc(var(--spacing)*2)",
  },
  button129: {
    height: "calc(var(--spacing)*6)",
    gap: "calc(var(--spacing)*1)",
    borderRadius: "calc(var(--radius) - 2px)",
    paddingInline: "calc(var(--spacing)*2)",
    fontSize: "var(--text-xs)",
    lineHeight: "var(--tw-leading,var(--text-xs--line-height))",
    "--tw-leading": null,
  },
  button130: {
    height: "calc(var(--spacing)*8)",
    gap: "calc(var(--spacing)*1.5)",
    borderRadius: "calc(var(--radius) - 2px)",
    paddingInline: "calc(var(--spacing)*3)",
  },
  button131: {
    height: "calc(var(--spacing)*10)",
    borderRadius: "calc(var(--radius) - 2px)",
    paddingInline: "calc(var(--spacing)*6)",
  },
  button132: {
    width: "calc(var(--spacing)*9)",
    height: "calc(var(--spacing)*9)",
  },
  button133: {
    width: "calc(var(--spacing)*6)",
    height: "calc(var(--spacing)*6)",
    borderRadius: "calc(var(--radius) - 2px)",
  },
  button134: {
    width: "calc(var(--spacing)*8)",
    height: "calc(var(--spacing)*8)",
  },
  button135: {
    width: "calc(var(--spacing)*10)",
    height: "calc(var(--spacing)*10)",
  },
  card136: {
    display: "flex",
    flexDirection: "column",
    gap: "calc(var(--spacing)*6)",
    borderRadius: "calc(var(--radius) + 4px)",
    borderStyle: "var(--tw-border-style)",
    borderWidth: "1px",
    backgroundColor: "var(--card)",
    paddingBlock: "calc(var(--spacing)*6)",
    color: "var(--card-foreground)",
    "--tw-shadow":
      "0 1px 3px 0 var(--tw-shadow-color,#0000001a),0 1px 2px -1px var(--tw-shadow-color,#0000001a)",
    boxShadow:
      "var(--tw-inset-shadow),var(--tw-inset-ring-shadow),var(--tw-ring-offset-shadow),var(--tw-ring-shadow),var(--tw-shadow)",
  },
  card137: {
    container: "card-header/inline-size",
    display: "grid",
    gridAutoRows: "min-content",
    gridTemplateRows: "auto auto",
    alignItems: "flex-start",
    gap: "calc(var(--spacing)*2)",
    paddingInline: "calc(var(--spacing)*6)",
  },
  card138: {
    "--tw-leading": "1",
    lineHeight: "1",
    "--tw-font-weight": "var(--font-weight-semibold)",
    fontWeight: "var(--font-weight-semibold)",
  },
  card139: {
    fontSize: "var(--text-sm)",
    lineHeight: "var(--tw-leading,var(--text-sm--line-height))",
    color: "var(--muted-foreground)",
    "--tw-leading": null,
  },
  card140: {
    gridColumnStart: "2",
    gridRow: "span 2/span 2",
    gridRowStart: "1",
    alignSelf: "flex-start",
    justifySelf: "flex-end",
  },
  card141: {
    paddingInline: "calc(var(--spacing)*6)",
  },
  card142: {
    display: "flex",
    alignItems: "center",
    paddingInline: "calc(var(--spacing)*6)",
  },
  dialog143: {
    position: "fixed",
    inset: "calc(var(--spacing)*0)",
    zIndex: "50",
    backgroundColor: "#00000080",
  },
  dialog144: {
    position: "fixed",
    top: "50%",
    left: "50%",
    zIndex: "50",
    display: "grid",
    width: "100%",
    maxWidth: "calc(100% - 2rem)",
    "--tw-translate-x": "-50%",
    translate: "var(--tw-translate-x)var(--tw-translate-y)",
    "--tw-translate-y": "-50%",
    gap: "calc(var(--spacing)*4)",
    borderRadius: "var(--radius)",
    borderStyle: "var(--tw-border-style)",
    borderWidth: "1px",
    backgroundColor: "var(--background)",
    padding: "calc(var(--spacing)*6)",
    "--tw-shadow":
      "0 10px 15px -3px var(--tw-shadow-color,#0000001a),0 4px 6px -4px var(--tw-shadow-color,#0000001a)",
    boxShadow:
      "var(--tw-inset-shadow),var(--tw-inset-ring-shadow),var(--tw-ring-offset-shadow),var(--tw-ring-shadow),var(--tw-shadow)",
    "--tw-duration": ".2s",
    transitionDuration: ".2s",
    "--tw-outline-style": "none",
    outlineStyle: "none",
    paddingInline: null,
    paddingBlock: null,
  },
  dialog145: {
    position: "absolute",
    top: "calc(var(--spacing)*4)",
    right: "calc(var(--spacing)*4)",
    borderRadius: "var(--radius-xs)",
    opacity: ".7",
    "--tw-ring-offset-color": "var(--background)",
    transitionProperty: "opacity",
    transitionTimingFunction:
      "var(--tw-ease,var(--default-transition-timing-function))",
    transitionDuration: "var(--tw-duration,var(--default-transition-duration))",
  },
  dialog146: {
    clipPath: "inset(50%)",
    whiteSpace: "nowrap",
    borderWidth: "0",
    width: "1px",
    height: "1px",
    margin: "-1px",
    padding: "0",
    position: "absolute",
    overflow: "hidden",
    paddingInline: null,
    paddingBlock: null,
    marginInline: null,
    marginBlock: null,
  },
  dialog147: {
    display: "flex",
    flexDirection: "column",
    gap: "calc(var(--spacing)*2)",
    textAlign: "center",
  },
  dialog148: {
    display: "flex",
    flexDirection: "column-reverse",
    gap: "calc(var(--spacing)*2)",
  },
  dialog149: {
    fontSize: "var(--text-lg)",
    lineHeight: "1",
    "--tw-leading": "1",
    "--tw-font-weight": "var(--font-weight-semibold)",
    fontWeight: "var(--font-weight-semibold)",
  },
});
export const classNames = {
  gpa0: `${stylex.props(styles.gpa0).className ?? ""} rank-gpa0`,
  gpa1: `${stylex.props(styles.gpa1).className ?? ""} rank-gpa1`,
  gpa2: `${stylex.props(styles.gpa2).className ?? ""} rank-gpa2`,
  layout3: `${stylex.props(styles.layout3).className ?? ""} rank-layout3`,
  Form4: `${stylex.props(styles.Form4).className ?? ""} rank-Form4`,
  Form5: `${stylex.props(styles.Form5).className ?? ""} rank-Form5`,
  Form6: `${stylex.props(styles.Form6).className ?? ""} rank-Form6`,
  Form7: `${stylex.props(styles.Form7).className ?? ""} rank-Form7`,
  Form8: `${stylex.props(styles.Form8).className ?? ""} rank-Form8`,
  Form9: `${stylex.props(styles.Form9).className ?? ""} rank-Form9`,
  Form10: `${stylex.props(styles.Form10).className ?? ""} rank-Form10`,
  Form11: `${stylex.props(styles.Form11).className ?? ""} rank-Form11`,
  Form12: `${stylex.props(styles.Form12).className ?? ""} rank-Form12`,
  Form13: `${stylex.props(styles.Form13).className ?? ""} rank-Form13`,
  Form14: `${stylex.props(styles.Form14).className ?? ""} rank-Form14`,
  Form15: `${stylex.props(styles.Form15).className ?? ""} rank-Form15`,
  Form16: `${stylex.props(styles.Form16).className ?? ""} rank-Form16`,
  Form17: `${stylex.props(styles.Form17).className ?? ""} rank-Form17`,
  Form18: `${stylex.props(styles.Form18).className ?? ""} rank-Form18`,
  Form19: `${stylex.props(styles.Form19).className ?? ""} rank-Form19`,
  met20: `${stylex.props(styles.met20).className ?? ""} rank-met20`,
  met21: `${stylex.props(styles.met21).className ?? ""} rank-met21`,
  met22: `${stylex.props(styles.met22).className ?? ""} rank-met22`,
  met23: `${stylex.props(styles.met23).className ?? ""} rank-met23`,
  met24: `${stylex.props(styles.met24).className ?? ""} rank-met24`,
  met25: `${stylex.props(styles.met25).className ?? ""} rank-met25`,
  met26: `${stylex.props(styles.met26).className ?? ""} rank-met26`,
  met27: `${stylex.props(styles.met27).className ?? ""} rank-met27`,
  met28: `${stylex.props(styles.met28).className ?? ""} rank-met28`,
  met29: `${stylex.props(styles.met29).className ?? ""} rank-met29`,
  home30: `${stylex.props(styles.home30).className ?? ""} rank-home30`,
  home31: `${stylex.props(styles.home31).className ?? ""} rank-home31`,
  home32: `${stylex.props(styles.home32).className ?? ""} rank-home32`,
  home33: `${stylex.props(styles.home33).className ?? ""} rank-home33`,
  home34: `${stylex.props(styles.home34).className ?? ""} rank-home34`,
  home35: `${stylex.props(styles.home35).className ?? ""} rank-home35`,
  home36: `${stylex.props(styles.home36).className ?? ""} rank-home36`,
  BranchesDisplay37: `${stylex.props(styles.BranchesDisplay37).className ?? ""} rank-BranchesDisplay37`,
  BranchesDisplay38: `${stylex.props(styles.BranchesDisplay38).className ?? ""} rank-BranchesDisplay38`,
  BranchesDisplay39: `${stylex.props(styles.BranchesDisplay39).className ?? ""} rank-BranchesDisplay39`,
  BranchesDisplay40: `${stylex.props(styles.BranchesDisplay40).className ?? ""} rank-BranchesDisplay40`,
  BranchesDisplay41: `${stylex.props(styles.BranchesDisplay41).className ?? ""} rank-BranchesDisplay41`,
  BranchesDisplay42: `${stylex.props(styles.BranchesDisplay42).className ?? ""} rank-BranchesDisplay42`,
  BranchesDisplay43: `${stylex.props(styles.BranchesDisplay43).className ?? ""} rank-BranchesDisplay43 campus-btn`,
  BranchesDisplay44: `${stylex.props(styles.BranchesDisplay44).className ?? ""} rank-BranchesDisplay44`,
  BranchesDisplay45: `${stylex.props(styles.BranchesDisplay45).className ?? ""} rank-BranchesDisplay45`,
  BranchesDisplay46: `${stylex.props(styles.BranchesDisplay46).className ?? ""} rank-BranchesDisplay46 campus-content`,
  BranchesDisplay47: `${stylex.props(styles.BranchesDisplay47).className ?? ""} rank-BranchesDisplay47`,
  BranchesDisplay48: `${stylex.props(styles.BranchesDisplay48).className ?? ""} rank-BranchesDisplay48`,
  BranchesDisplay49: `${stylex.props(styles.BranchesDisplay49).className ?? ""} rank-BranchesDisplay49`,
  BranchesDisplay50: `${stylex.props(styles.BranchesDisplay50).className ?? ""} rank-BranchesDisplay50`,
  HowItWorksDropdown51: `${stylex.props(styles.HowItWorksDropdown51).className ?? ""} rank-HowItWorksDropdown51 content`,
  HowItWorksDropdown52: `${stylex.props(styles.HowItWorksDropdown52).className ?? ""} rank-HowItWorksDropdown52`,
  HowItWorksDropdown53: `${stylex.props(styles.HowItWorksDropdown53).className ?? ""} rank-HowItWorksDropdown53`,
  HowItWorksDropdown54: `${stylex.props(styles.HowItWorksDropdown54).className ?? ""} rank-HowItWorksDropdown54`,
  HowItWorksDropdown55: `${stylex.props(styles.HowItWorksDropdown55).className ?? ""} rank-HowItWorksDropdown55`,
  HowItWorksDropdown56: `${stylex.props(styles.HowItWorksDropdown56).className ?? ""} rank-HowItWorksDropdown56`,
  HowItWorksDropdown57: `${stylex.props(styles.HowItWorksDropdown57).className ?? ""} rank-HowItWorksDropdown57`,
  HowItWorksDropdown58: `${stylex.props(styles.HowItWorksDropdown58).className ?? ""} rank-HowItWorksDropdown58`,
  HowItWorksDropdown59: `${stylex.props(styles.HowItWorksDropdown59).className ?? ""} rank-HowItWorksDropdown59`,
  HowItWorksDropdown60: `${stylex.props(styles.HowItWorksDropdown60).className ?? ""} rank-HowItWorksDropdown60`,
  HowItWorksDropdown61: `${stylex.props(styles.HowItWorksDropdown61).className ?? ""} rank-HowItWorksDropdown61`,
  HowItWorksDropdown62: `${stylex.props(styles.HowItWorksDropdown62).className ?? ""} rank-HowItWorksDropdown62`,
  HowItWorksDropdown63: `${stylex.props(styles.HowItWorksDropdown63).className ?? ""} rank-HowItWorksDropdown63`,
  HowItWorksDropdown64: `${stylex.props(styles.HowItWorksDropdown64).className ?? ""} rank-HowItWorksDropdown64`,
  HowItWorksDropdown65: `${stylex.props(styles.HowItWorksDropdown65).className ?? ""} rank-HowItWorksDropdown65`,
  HowItWorksDropdown66: `${stylex.props(styles.HowItWorksDropdown66).className ?? ""} rank-HowItWorksDropdown66`,
  HowItWorksDropdown67: `${stylex.props(styles.HowItWorksDropdown67).className ?? ""} rank-HowItWorksDropdown67`,
  Navbar68: `${stylex.props(styles.Navbar68).className ?? ""} rank-Navbar68`,
  Navbar69: `${stylex.props(styles.Navbar69).className ?? ""} rank-Navbar69`,
  Navbar70: `${stylex.props(styles.Navbar70).className ?? ""} rank-Navbar70`,
  Navbar71: `${stylex.props(styles.Navbar71).className ?? ""} rank-Navbar71`,
  Navbar72: `${stylex.props(styles.Navbar72).className ?? ""} rank-Navbar72`,
  Navbar73: `${stylex.props(styles.Navbar73).className ?? ""} rank-Navbar73`,
  Navbar74: `${stylex.props(styles.Navbar74).className ?? ""} rank-Navbar74`,
  CourseList75: `${stylex.props(styles.CourseList75).className ?? ""} rank-CourseList75`,
  CourseList76: `${stylex.props(styles.CourseList76).className ?? ""} rank-CourseList76`,
  CourseList77: `${stylex.props(styles.CourseList77).className ?? ""} rank-CourseList77`,
  CourseList78: `${stylex.props(styles.CourseList78).className ?? ""} rank-CourseList78`,
  CourseList79: `${stylex.props(styles.CourseList79).className ?? ""} rank-CourseList79`,
  CourseList80: `${stylex.props(styles.CourseList80).className ?? ""} rank-CourseList80`,
  CycleSelect81: `${stylex.props(styles.CycleSelect81).className ?? ""} rank-CycleSelect81`,
  CycleSelect82: `${stylex.props(styles.CycleSelect82).className ?? ""} rank-CycleSelect82`,
  CycleSelect83: `${stylex.props(styles.CycleSelect83).className ?? ""} rank-CycleSelect83`,
  CycleSelect84: `${stylex.props(styles.CycleSelect84).className ?? ""} rank-CycleSelect84`,
  CycleSelect85: `${stylex.props(styles.CycleSelect85).className ?? ""} rank-CycleSelect85`,
  GpaTable86: `${stylex.props(styles.GpaTable86).className ?? ""} rank-GpaTable86`,
  GpaTable87: `${stylex.props(styles.GpaTable87).className ?? ""} rank-GpaTable87`,
  GpaTable88: `${stylex.props(styles.GpaTable88).className ?? ""} rank-GpaTable88`,
  GpaTable89: `${stylex.props(styles.GpaTable89).className ?? ""} rank-GpaTable89`,
  GpaTable90: `${stylex.props(styles.GpaTable90).className ?? ""} rank-GpaTable90`,
  GpaTable91: `${stylex.props(styles.GpaTable91).className ?? ""} rank-GpaTable91`,
  GpaTable92: `${stylex.props(styles.GpaTable92).className ?? ""} rank-GpaTable92`,
  GpaTable93: `${stylex.props(styles.GpaTable93).className ?? ""} rank-GpaTable93`,
  GpaTable94: `${stylex.props(styles.GpaTable94).className ?? ""} rank-GpaTable94`,
  GpaTable95: `${stylex.props(styles.GpaTable95).className ?? ""} rank-GpaTable95`,
  GradingInfoDropdown96: `${stylex.props(styles.GradingInfoDropdown96).className ?? ""} rank-GradingInfoDropdown96`,
  GradingInfoDropdown97: `${stylex.props(styles.GradingInfoDropdown97).className ?? ""} rank-GradingInfoDropdown97`,
  GradingInfoDropdown98: `${stylex.props(styles.GradingInfoDropdown98).className ?? ""} rank-GradingInfoDropdown98`,
  GradingInfoDropdown99: `${stylex.props(styles.GradingInfoDropdown99).className ?? ""} rank-GradingInfoDropdown99`,
  GradingInfoDropdown100: `${stylex.props(styles.GradingInfoDropdown100).className ?? ""} rank-GradingInfoDropdown100`,
  GradingInfoDropdown101: `${stylex.props(styles.GradingInfoDropdown101).className ?? ""} rank-GradingInfoDropdown101`,
  GradingInfoDropdown102: `${stylex.props(styles.GradingInfoDropdown102).className ?? ""} rank-GradingInfoDropdown102`,
  GradingInfoDropdown103: `${stylex.props(styles.GradingInfoDropdown103).className ?? ""} rank-GradingInfoDropdown103`,
  GradingInfoDropdown104: `${stylex.props(styles.GradingInfoDropdown104).className ?? ""} rank-GradingInfoDropdown104`,
  GradingInfoDropdown105: `${stylex.props(styles.GradingInfoDropdown105).className ?? ""} rank-GradingInfoDropdown105`,
  HonorsCheck106: `${stylex.props(styles.HonorsCheck106).className ?? ""} rank-HonorsCheck106`,
  HonorsCheck107: `${stylex.props(styles.HonorsCheck107).className ?? ""} rank-HonorsCheck107`,
  HonorsCheck108: `${stylex.props(styles.HonorsCheck108).className ?? ""} rank-HonorsCheck108`,
  HonorsCheck109: `${stylex.props(styles.HonorsCheck109).className ?? ""} rank-HonorsCheck109`,
  SemButton110: `${stylex.props(styles.SemButton110).className ?? ""} rank-SemButton110`,
  SemButton111: `${stylex.props(styles.SemButton111).className ?? ""} rank-SemButton111`,
  SemButton112: `${stylex.props(styles.SemButton112).className ?? ""} rank-SemButton112`,
  SemButton113: `${stylex.props(styles.SemButton113).className ?? ""} rank-SemButton113`,
  SemPicker114: `${stylex.props(styles.SemPicker114).className ?? ""} rank-SemPicker114`,
  SemPicker115: `${stylex.props(styles.SemPicker115).className ?? ""} rank-SemPicker115`,
  SemPicker116: `${stylex.props(styles.SemPicker116).className ?? ""} rank-SemPicker116`,
  SemPicker117: `${stylex.props(styles.SemPicker117).className ?? ""} rank-SemPicker117`,
  SemPicker118: `${stylex.props(styles.SemPicker118).className ?? ""} rank-SemPicker118`,
  StreamSelect119: `${stylex.props(styles.StreamSelect119).className ?? ""} rank-StreamSelect119`,
  StreamSelect120: `${stylex.props(styles.StreamSelect120).className ?? ""} rank-StreamSelect120`,
  button121: `${stylex.props(styles.button121).className ?? ""} rank-button121`,
  button122: `${stylex.props(styles.button122).className ?? ""} rank-button122`,
  button123: `${stylex.props(styles.button123).className ?? ""} rank-button123`,
  button124: `${stylex.props(styles.button124).className ?? ""} rank-button124`,
  button125: `${stylex.props(styles.button125).className ?? ""} rank-button125`,
  button126: `${stylex.props(styles.button126).className ?? ""} rank-button126`,
  button127: `${stylex.props(styles.button127).className ?? ""} rank-button127`,
  button128: `${stylex.props(styles.button128).className ?? ""} rank-button128`,
  button129: `${stylex.props(styles.button129).className ?? ""} rank-button129`,
  button130: `${stylex.props(styles.button130).className ?? ""} rank-button130`,
  button131: `${stylex.props(styles.button131).className ?? ""} rank-button131`,
  button132: `${stylex.props(styles.button132).className ?? ""} rank-button132`,
  button133: `${stylex.props(styles.button133).className ?? ""} rank-button133`,
  button134: `${stylex.props(styles.button134).className ?? ""} rank-button134`,
  button135: `${stylex.props(styles.button135).className ?? ""} rank-button135`,
  card136: `${stylex.props(styles.card136).className ?? ""} rank-card136`,
  card137: `${stylex.props(styles.card137).className ?? ""} rank-card137`,
  card138: `${stylex.props(styles.card138).className ?? ""} rank-card138`,
  card139: `${stylex.props(styles.card139).className ?? ""} rank-card139`,
  card140: `${stylex.props(styles.card140).className ?? ""} rank-card140`,
  card141: `${stylex.props(styles.card141).className ?? ""} rank-card141`,
  card142: `${stylex.props(styles.card142).className ?? ""} rank-card142`,
  dialog143: `${stylex.props(styles.dialog143).className ?? ""} rank-dialog143`,
  dialog144: `${stylex.props(styles.dialog144).className ?? ""} rank-dialog144`,
  dialog145: `${stylex.props(styles.dialog145).className ?? ""} rank-dialog145`,
  dialog146: `${stylex.props(styles.dialog146).className ?? ""} rank-dialog146`,
  dialog147: `${stylex.props(styles.dialog147).className ?? ""} rank-dialog147`,
  dialog148: `${stylex.props(styles.dialog148).className ?? ""} rank-dialog148`,
  dialog149: `${stylex.props(styles.dialog149).className ?? ""} rank-dialog149`,
};

export const styleEntries = [
  ["rank-gpa0", styles.gpa0],
  ["rank-gpa1", styles.gpa1],
  ["rank-gpa2", styles.gpa2],
  ["rank-layout3", styles.layout3],
  ["rank-Form4", styles.Form4],
  ["rank-Form5", styles.Form5],
  ["rank-Form6", styles.Form6],
  ["rank-Form7", styles.Form7],
  ["rank-Form8", styles.Form8],
  ["rank-Form9", styles.Form9],
  ["rank-Form10", styles.Form10],
  ["rank-Form11", styles.Form11],
  ["rank-Form12", styles.Form12],
  ["rank-Form13", styles.Form13],
  ["rank-Form14", styles.Form14],
  ["rank-Form15", styles.Form15],
  ["rank-Form16", styles.Form16],
  ["rank-Form17", styles.Form17],
  ["rank-Form18", styles.Form18],
  ["rank-Form19", styles.Form19],
  ["rank-met20", styles.met20],
  ["rank-met21", styles.met21],
  ["rank-met22", styles.met22],
  ["rank-met23", styles.met23],
  ["rank-met24", styles.met24],
  ["rank-met25", styles.met25],
  ["rank-met26", styles.met26],
  ["rank-met27", styles.met27],
  ["rank-met28", styles.met28],
  ["rank-met29", styles.met29],
  ["rank-home30", styles.home30],
  ["rank-home31", styles.home31],
  ["rank-home32", styles.home32],
  ["rank-home33", styles.home33],
  ["rank-home34", styles.home34],
  ["rank-home35", styles.home35],
  ["rank-home36", styles.home36],
  ["rank-BranchesDisplay37", styles.BranchesDisplay37],
  ["rank-BranchesDisplay38", styles.BranchesDisplay38],
  ["rank-BranchesDisplay39", styles.BranchesDisplay39],
  ["rank-BranchesDisplay40", styles.BranchesDisplay40],
  ["rank-BranchesDisplay41", styles.BranchesDisplay41],
  ["rank-BranchesDisplay42", styles.BranchesDisplay42],
  ["rank-BranchesDisplay43", styles.BranchesDisplay43],
  ["rank-BranchesDisplay44", styles.BranchesDisplay44],
  ["rank-BranchesDisplay45", styles.BranchesDisplay45],
  ["rank-BranchesDisplay46", styles.BranchesDisplay46],
  ["rank-BranchesDisplay47", styles.BranchesDisplay47],
  ["rank-BranchesDisplay48", styles.BranchesDisplay48],
  ["rank-BranchesDisplay49", styles.BranchesDisplay49],
  ["rank-BranchesDisplay50", styles.BranchesDisplay50],
  ["rank-HowItWorksDropdown51", styles.HowItWorksDropdown51],
  ["rank-HowItWorksDropdown52", styles.HowItWorksDropdown52],
  ["rank-HowItWorksDropdown53", styles.HowItWorksDropdown53],
  ["rank-HowItWorksDropdown54", styles.HowItWorksDropdown54],
  ["rank-HowItWorksDropdown55", styles.HowItWorksDropdown55],
  ["rank-HowItWorksDropdown56", styles.HowItWorksDropdown56],
  ["rank-HowItWorksDropdown57", styles.HowItWorksDropdown57],
  ["rank-HowItWorksDropdown58", styles.HowItWorksDropdown58],
  ["rank-HowItWorksDropdown59", styles.HowItWorksDropdown59],
  ["rank-HowItWorksDropdown60", styles.HowItWorksDropdown60],
  ["rank-HowItWorksDropdown61", styles.HowItWorksDropdown61],
  ["rank-HowItWorksDropdown62", styles.HowItWorksDropdown62],
  ["rank-HowItWorksDropdown63", styles.HowItWorksDropdown63],
  ["rank-HowItWorksDropdown64", styles.HowItWorksDropdown64],
  ["rank-HowItWorksDropdown65", styles.HowItWorksDropdown65],
  ["rank-HowItWorksDropdown66", styles.HowItWorksDropdown66],
  ["rank-HowItWorksDropdown67", styles.HowItWorksDropdown67],
  ["rank-Navbar68", styles.Navbar68],
  ["rank-Navbar69", styles.Navbar69],
  ["rank-Navbar70", styles.Navbar70],
  ["rank-Navbar71", styles.Navbar71],
  ["rank-Navbar72", styles.Navbar72],
  ["rank-Navbar73", styles.Navbar73],
  ["rank-Navbar74", styles.Navbar74],
  ["rank-CourseList75", styles.CourseList75],
  ["rank-CourseList76", styles.CourseList76],
  ["rank-CourseList77", styles.CourseList77],
  ["rank-CourseList78", styles.CourseList78],
  ["rank-CourseList79", styles.CourseList79],
  ["rank-CourseList80", styles.CourseList80],
  ["rank-CycleSelect81", styles.CycleSelect81],
  ["rank-CycleSelect82", styles.CycleSelect82],
  ["rank-CycleSelect83", styles.CycleSelect83],
  ["rank-CycleSelect84", styles.CycleSelect84],
  ["rank-CycleSelect85", styles.CycleSelect85],
  ["rank-GpaTable86", styles.GpaTable86],
  ["rank-GpaTable87", styles.GpaTable87],
  ["rank-GpaTable88", styles.GpaTable88],
  ["rank-GpaTable89", styles.GpaTable89],
  ["rank-GpaTable90", styles.GpaTable90],
  ["rank-GpaTable91", styles.GpaTable91],
  ["rank-GpaTable92", styles.GpaTable92],
  ["rank-GpaTable93", styles.GpaTable93],
  ["rank-GpaTable94", styles.GpaTable94],
  ["rank-GpaTable95", styles.GpaTable95],
  ["rank-GradingInfoDropdown96", styles.GradingInfoDropdown96],
  ["rank-GradingInfoDropdown97", styles.GradingInfoDropdown97],
  ["rank-GradingInfoDropdown98", styles.GradingInfoDropdown98],
  ["rank-GradingInfoDropdown99", styles.GradingInfoDropdown99],
  ["rank-GradingInfoDropdown100", styles.GradingInfoDropdown100],
  ["rank-GradingInfoDropdown101", styles.GradingInfoDropdown101],
  ["rank-GradingInfoDropdown102", styles.GradingInfoDropdown102],
  ["rank-GradingInfoDropdown103", styles.GradingInfoDropdown103],
  ["rank-GradingInfoDropdown104", styles.GradingInfoDropdown104],
  ["rank-GradingInfoDropdown105", styles.GradingInfoDropdown105],
  ["rank-HonorsCheck106", styles.HonorsCheck106],
  ["rank-HonorsCheck107", styles.HonorsCheck107],
  ["rank-HonorsCheck108", styles.HonorsCheck108],
  ["rank-HonorsCheck109", styles.HonorsCheck109],
  ["rank-SemButton110", styles.SemButton110],
  ["rank-SemButton111", styles.SemButton111],
  ["rank-SemButton112", styles.SemButton112],
  ["rank-SemButton113", styles.SemButton113],
  ["rank-SemPicker114", styles.SemPicker114],
  ["rank-SemPicker115", styles.SemPicker115],
  ["rank-SemPicker116", styles.SemPicker116],
  ["rank-SemPicker117", styles.SemPicker117],
  ["rank-SemPicker118", styles.SemPicker118],
  ["rank-StreamSelect119", styles.StreamSelect119],
  ["rank-StreamSelect120", styles.StreamSelect120],
  ["rank-button121", styles.button121],
  ["rank-button122", styles.button122],
  ["rank-button123", styles.button123],
  ["rank-button124", styles.button124],
  ["rank-button125", styles.button125],
  ["rank-button126", styles.button126],
  ["rank-button127", styles.button127],
  ["rank-button128", styles.button128],
  ["rank-button129", styles.button129],
  ["rank-button130", styles.button130],
  ["rank-button131", styles.button131],
  ["rank-button132", styles.button132],
  ["rank-button133", styles.button133],
  ["rank-button134", styles.button134],
  ["rank-button135", styles.button135],
  ["rank-card136", styles.card136],
  ["rank-card137", styles.card137],
  ["rank-card138", styles.card138],
  ["rank-card139", styles.card139],
  ["rank-card140", styles.card140],
  ["rank-card141", styles.card141],
  ["rank-card142", styles.card142],
  ["rank-dialog143", styles.dialog143],
  ["rank-dialog144", styles.dialog144],
  ["rank-dialog145", styles.dialog145],
  ["rank-dialog146", styles.dialog146],
  ["rank-dialog147", styles.dialog147],
  ["rank-dialog148", styles.dialog148],
  ["rank-dialog149", styles.dialog149],
];
